# Header
brand: "@nberserk's log"
navbar_brand: nberserk's traces

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
widgets:
- about         # See also: `about_content`
- tagcloud
- archive
- recent_posts
about_widget_content: >
  <a href="https://twitter.com/darrenha?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @darrenha</a>
  <a class="github-button" href="https://github.com/nberserk" data-show-count="true" aria-label="Follow @nberserk on GitHub">Follow @nberserk</a>
  <hr/>

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics: UA-63706532-1

favicon:
twitter_id: darrenha
google_plus:
fb_admins:
fb_app_id:



